// @ts-ignore - importing from source to use patched astTransform
import {
  defaultMarkdownTheme,
  type MarkdownTheme,
} from 'react-native-nitro-markdown/src';

// v0.4.x removed lightMarkdownTheme/darkMarkdownTheme — define locally
const lightMarkdownTheme: MarkdownTheme = defaultMarkdownTheme;

const darkMarkdownTheme: MarkdownTheme = {
  ...defaultMarkdownTheme,
  colors: {
    text: '#e2e8f0',
    textMuted: '#94a3b8',
    heading: '#f1f5f9',
    link: '#60a5fa',
    code: '#e2e8f0',
    codeBackground: '#1e293b',
    codeLanguage: '#64748b',
    blockquote: '#334155',
    border: '#334155',
    surface: '#1e293b',
    surfaceLight: '#0f172a',
    accent: '#60a5fa',
    tableBorder: '#334155',
    tableHeader: '#1e293b',
    tableHeaderText: '#94a3b8',
    tableRowEven: 'transparent',
    tableRowOdd: '#1e293b',
  },
};

export type ParticleOverlayConfig = {
  particles: string[];
  count: number;
  size: [number, number];
  duration: [number, number];
  sway: [number, number];
  swayDivisor: number;
  rotation: [number, number];
  rotationDivisor: number;
  opacity?: [number, number];
  color?: string | {light: string; dark: string};
  behindFraction?: number;
};

export type CustomRendererConfig = {
  horizontalRule?: {emojis: string[]};
  headingDecoration?: {type: 'santa-hat'; size: number};
};

export type ThemeConfig = {
  icon: string;
  author?: string;
  light: MarkdownTheme;
  dark: MarkdownTheme;
  background: {light: string; dark: string};
  overlay?: ParticleOverlayConfig;
  customRenderers?: CustomRendererConfig;
  fonts?: {
    regular?: string;
    heading?: string;
    mono?: string;
  };
};

export const customThemes = {
  default: {
    icon: '⚪',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        surface: '#f5f5f5',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        surface: '#2a2a2a',
      },
    },
    background: {light: '#ffffff', dark: '#1a1a1a'},
  },
  ocean: {
    icon: '🌊',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#1e3a5f',
        textMuted: '#4a6a8f',
        heading: '#0c2340',
        link: '#0077b6',
        code: '#007aa9',
        codeBackground: '#e0f4ff',
        blockquote: '#0096c7',
        accent: '#48cae4',
        border: '#90e0ef',
        tableBorder: '#90e0ef',
        tableHeader: '#caf0f8',
        tableHeaderText: '#03045e',
        tableRowEven: '#ffffff',
        tableRowOdd: '#f0faff',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#caf0f8',
        textMuted: '#90c0d8',
        heading: '#90e0ef',
        link: '#48cae4',
        code: '#00b4d8',
        codeBackground: '#023e8a',
        blockquote: '#0096c7',
        accent: '#48cae4',
        border: '#0077b6',
        surface: '#03045e',
        surfaceLight: '#023e8a',
        tableBorder: '#0077b6',
        tableHeader: '#023e8a',
        tableHeaderText: '#90e0ef',
        tableRowEven: '#03045e',
        tableRowOdd: '#0a1628',
      },
    },
    background: {light: '#f0faff', dark: '#03045e'},
  },
  forest: {
    icon: '🌲',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#2d3b2d',
        textMuted: '#5a6b5a',
        heading: '#1a2e1a',
        link: '#2d6a4f',
        code: '#398060',
        codeBackground: '#d8f3dc',
        blockquote: '#52b788',
        accent: '#74c69d',
        border: '#95d5b2',
        tableBorder: '#95d5b2',
        tableHeader: '#d8f3dc',
        tableHeaderText: '#1b4332',
        tableRowEven: '#ffffff',
        tableRowOdd: '#f0fff4',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#d8f3dc',
        textMuted: '#a0c3ac',
        heading: '#95d5b2',
        link: '#74c69d',
        code: '#52b788',
        codeBackground: '#1b4332',
        blockquote: '#40916c',
        accent: '#74c69d',
        border: '#2d6a4f',
        surface: '#081c15',
        surfaceLight: '#1b4332',
        tableBorder: '#2d6a4f',
        tableHeader: '#1b4332',
        tableHeaderText: '#95d5b2',
        tableRowEven: '#081c15',
        tableRowOdd: '#0d2818',
      },
    },
    background: {light: '#f0fff4', dark: '#081c15'},
  },
  sunset: {
    icon: '🌅',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#5c3d2e',
        textMuted: '#8b6b5a',
        heading: '#3d2314',
        link: '#c74827',
        code: '#b25a0d',
        codeBackground: '#ffeee6',
        blockquote: '#e07a5f',
        accent: '#f2994a',
        border: '#ffcdb2',
        tableBorder: '#ffcdb2',
        tableHeader: '#ffe5d9',
        tableHeaderText: '#6d4c41',
        tableRowEven: '#ffffff',
        tableRowOdd: '#fff8f5',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#ffcdb2',
        textMuted: '#c9a090',
        heading: '#ffb4a2',
        link: '#e5989b',
        code: '#f2994a',
        codeBackground: '#5c3d2e',
        blockquote: '#e07a5f',
        accent: '#f2994a',
        border: '#6d4c41',
        surface: '#3d2314',
        surfaceLight: '#5c3d2e',
        tableBorder: '#6d4c41',
        tableHeader: '#5c3d2e',
        tableHeaderText: '#ffcdb2',
        tableRowEven: '#3d2314',
        tableRowOdd: '#4a2c1a',
      },
    },
    background: {light: '#fff8f5', dark: '#3d2314'},
  },
  lavender: {
    icon: '💜',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#4a4063',
        textMuted: '#756b8e',
        heading: '#2d2640',
        link: '#7c3aed',
        code: '#7a4ff7',
        codeBackground: '#ede9fe',
        blockquote: '#8b5cf6',
        accent: '#a78bfa',
        border: '#c4b5fd',
        tableBorder: '#c4b5fd',
        tableHeader: '#ede9fe',
        tableHeaderText: '#5b21b6',
        tableRowEven: '#ffffff',
        tableRowOdd: '#faf5ff',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#e9d5ff',
        textMuted: '#b9a5cf',
        heading: '#c4b5fd',
        link: '#a78bfa',
        code: '#c084fc',
        codeBackground: '#3b0764',
        blockquote: '#8b5cf6',
        accent: '#a78bfa',
        border: '#6b21a8',
        surface: '#2e1065',
        surfaceLight: '#3b0764',
        tableBorder: '#6b21a8',
        tableHeader: '#3b0764',
        tableHeaderText: '#c4b5fd',
        tableRowEven: '#2e1065',
        tableRowOdd: '#1e0a3e',
      },
    },
    background: {light: '#faf5ff', dark: '#2e1065'},
  },
  winter: {
    icon: '❄️',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#2c3e50',
        textMuted: '#657281',
        heading: '#1a252f',
        link: '#2e75b5',
        code: '#2c75b6',
        codeBackground: '#e8f0fe',
        blockquote: '#a4c2f4',
        accent: '#5b9bd5',
        border: '#c6d9f1',
        tableBorder: '#c6d9f1',
        tableHeader: '#e8f0fe',
        tableHeaderText: '#2c3e50',
        tableRowEven: '#ffffff',
        tableRowOdd: '#f4f8ff',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#cfe2f3',
        textMuted: '#8eaec7',
        heading: '#a4c2f4',
        link: '#6fa8dc',
        code: '#5b9bd5',
        codeBackground: '#1a2a3e',
        blockquote: '#3d6b99',
        accent: '#6fa8dc',
        border: '#2c4a6e',
        surface: '#0d1b2a',
        surfaceLight: '#1a2a3e',
        tableBorder: '#2c4a6e',
        tableHeader: '#1a2a3e',
        tableHeaderText: '#a4c2f4',
        tableRowEven: '#0d1b2a',
        tableRowOdd: '#112233',
      },
    },
    background: {light: '#f4f8ff', dark: '#0d1b2a'},
    overlay: {
      particles: ['❄', '❅', '❆', '✦', '•'],
      count: 30,
      size: [8, 22],
      duration: [6000, 14000],
      sway: [15, 45],
      swayDivisor: 3,
      rotation: [15, 60],
      rotationDivisor: 2,
      opacity: [0.3, 0.8],
      color: {light: '#a4c2f4', dark: '#ffffff'},
    },
  },
  spring: {
    icon: '🌸',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#3b4f2a',
        textMuted: '#5e7a4b',
        heading: '#2a3d1a',
        link: '#db1f57',
        code: '#be496a',
        codeBackground: '#fce4ec',
        blockquote: '#f48fb1',
        accent: '#e75480',
        border: '#f8bbd0',
        tableBorder: '#f8bbd0',
        tableHeader: '#fce4ec',
        tableHeaderText: '#880e4f',
        tableRowEven: '#ffffff',
        tableRowOdd: '#fef7f9',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#f8d7e3',
        textMuted: '#c9a0b2',
        heading: '#f48fb1',
        link: '#f06292',
        code: '#e75480',
        codeBackground: '#4a1a2e',
        blockquote: '#c2185b',
        accent: '#f06292',
        border: '#6a1b3d',
        surface: '#2a0e1e',
        surfaceLight: '#4a1a2e',
        tableBorder: '#6a1b3d',
        tableHeader: '#4a1a2e',
        tableHeaderText: '#f48fb1',
        tableRowEven: '#2a0e1e',
        tableRowOdd: '#351428',
      },
    },
    background: {light: '#fef7f9', dark: '#2a0e1e'},
    overlay: {
      particles: ['🌸', '🌸', '🌸', '💮', '🏵️'],
      count: 25,
      size: [10, 20],
      duration: [9000, 18000],
      sway: [20, 70],
      swayDivisor: 5,
      rotation: [20, 100],
      rotationDivisor: 3,
      opacity: [0.6, 1.0],
    },
  },
  summer: {
    icon: '☀️',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#5c4a1e',
        textMuted: '#86723e',
        heading: '#3d3010',
        link: '#956d0f',
        code: '#936e0c',
        codeBackground: '#fff8e1',
        blockquote: '#ffc107',
        accent: '#ffb300',
        border: '#ffe082',
        tableBorder: '#ffe082',
        tableHeader: '#fff8e1',
        tableHeaderText: '#5c4a1e',
        tableRowEven: '#ffffff',
        tableRowOdd: '#fffcf0',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#ffe082',
        textMuted: '#c4a44a',
        heading: '#ffd54f',
        link: '#ffca28',
        code: '#ffb300',
        codeBackground: '#3e2c06',
        blockquote: '#f9a825',
        accent: '#ffca28',
        border: '#5c4a1e',
        surface: '#261c04',
        surfaceLight: '#3e2c06',
        tableBorder: '#5c4a1e',
        tableHeader: '#3e2c06',
        tableHeaderText: '#ffd54f',
        tableRowEven: '#261c04',
        tableRowOdd: '#302208',
      },
    },
    background: {light: '#fffcf0', dark: '#261c04'},
  },
  autumn: {
    icon: '🍂',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#5d3a1a',
        textMuted: '#8b6942',
        heading: '#3e2410',
        link: '#b9511e',
        code: '#b0581a',
        codeBackground: '#fbe9da',
        blockquote: '#e65100',
        accent: '#f57c00',
        border: '#ffcc80',
        tableBorder: '#ffcc80',
        tableHeader: '#fbe9da',
        tableHeaderText: '#5d3a1a',
        tableRowEven: '#ffffff',
        tableRowOdd: '#fdf5ee',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#ffcc80',
        textMuted: '#c49050',
        heading: '#ffb74d',
        link: '#ff9800',
        code: '#f57c00',
        codeBackground: '#3e2010',
        blockquote: '#e65100',
        accent: '#ff9800',
        border: '#5d3a1a',
        surface: '#2a1508',
        surfaceLight: '#3e2010',
        tableBorder: '#5d3a1a',
        tableHeader: '#3e2010',
        tableHeaderText: '#ffb74d',
        tableRowEven: '#2a1508',
        tableRowOdd: '#331a0c',
      },
    },
    background: {light: '#fdf5ee', dark: '#2a1508'},
    overlay: {
      particles: ['🍂', '🍁', '🍃', '🍂', '🍁'],
      count: 20,
      size: [16, 28],
      duration: [8000, 18000],
      sway: [30, 90],
      swayDivisor: 4,
      rotation: [30, 180],
      rotationDivisor: 2,
      behindFraction: 0.4,
    },
  },
  christmas: {
    icon: '🎄',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#2e4033',
        textMuted: '#59785e',
        heading: '#b71c1c',
        link: '#c62828',
        code: '#2e7d32',
        codeBackground: '#e8f5e9',
        blockquote: '#c62828',
        accent: '#d32f2f',
        border: '#c8e6c9',
        tableBorder: '#c8e6c9',
        tableHeader: '#ffebee',
        tableHeaderText: '#b71c1c',
        tableRowEven: '#ffffff',
        tableRowOdd: '#f1f8f2',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#c8e6c9',
        textMuted: '#81a784',
        heading: '#ef5350',
        link: '#ef9a9a',
        code: '#81c784',
        codeBackground: '#1b3a1e',
        blockquote: '#c62828',
        accent: '#ef5350',
        border: '#2e5930',
        surface: '#0d1f10',
        surfaceLight: '#1b3a1e',
        tableBorder: '#2e5930',
        tableHeader: '#2a1010',
        tableHeaderText: '#ef9a9a',
        tableRowEven: '#0d1f10',
        tableRowOdd: '#142818',
      },
    },
    background: {light: '#f1f8f2', dark: '#0d1f10'},
    customRenderers: {
      horizontalRule: {emojis: ['🎄', '⭐', '🎄']},
      headingDecoration: {type: 'santa-hat', size: 30},
    },
  },
  easter: {
    icon: '🐣',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#4a3f5c',
        textMuted: '#766b87',
        heading: '#6a1b9a',
        link: '#a944bb',
        code: '#557a2d',
        codeBackground: '#f3e5f5',
        blockquote: '#ce93d8',
        accent: '#ab47bc',
        border: '#e1bee7',
        tableBorder: '#e1bee7',
        tableHeader: '#f3e5f5',
        tableHeaderText: '#6a1b9a',
        tableRowEven: '#ffffff',
        tableRowOdd: '#fdf2ff',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#e1bee7',
        textMuted: '#b088b8',
        heading: '#ce93d8',
        link: '#ba68c8',
        code: '#aed581',
        codeBackground: '#301540',
        blockquote: '#8e24aa',
        accent: '#ba68c8',
        border: '#4a1860',
        surface: '#1a0a28',
        surfaceLight: '#301540',
        tableBorder: '#4a1860',
        tableHeader: '#301540',
        tableHeaderText: '#ce93d8',
        tableRowEven: '#1a0a28',
        tableRowOdd: '#221032',
      },
    },
    background: {light: '#fdf2ff', dark: '#1a0a28'},
  },
  dude: {
    icon: '🎳',
    author: 'The Dude',
    light: {
      ...lightMarkdownTheme,
      colors: {
        ...lightMarkdownTheme.colors,
        text: '#3e2723',
        textMuted: '#795548',
        heading: '#4e342e',
        link: '#bf360c',
        code: '#4e342e',
        codeBackground: '#efebe9',
        codeLanguage: '#8d6e63',
        blockquote: '#d7ccc8',
        border: '#bcaaa4',
        surface: '#efebe9',
        surfaceLight: '#fbe9e7',
        accent: '#bf360c',
        tableBorder: '#bcaaa4',
        tableHeader: '#efebe9',
        tableHeaderText: '#5d4037',
        tableRowEven: 'transparent',
        tableRowOdd: '#efebe9',
        background: '#fff8e1',
      },
    },
    dark: {
      ...darkMarkdownTheme,
      colors: {
        ...darkMarkdownTheme.colors,
        text: '#d7ccc8',
        textMuted: '#977868',
        heading: '#efebe9',
        link: '#ff8a65',
        code: '#d7ccc8',
        codeBackground: '#3e2723',
        codeLanguage: '#977868',
        blockquote: '#4e342e',
        border: '#5d4037',
        surface: '#3e2723',
        surfaceLight: '#2c1a12',
        accent: '#ff8a65',
        tableBorder: '#5d4037',
        tableHeader: '#3e2723',
        tableHeaderText: '#a1887f',
        tableRowEven: 'transparent',
        tableRowOdd: '#3e2723',
        background: '#1b0e04',
      },
    },
    background: {light: '#fff8e1', dark: '#1b0e04'},
    customRenderers: {
      horizontalRule: {emojis: ['🎳', '🥛', '🎳']},
    },
  },
} satisfies Record<string, ThemeConfig>;

export type ThemeName = keyof typeof customThemes;

const hiddenThemes: ThemeName[] = ['dude'];

// themeNames controls which themes are cycled through — hidden themes are excluded
export const themeNames = (Object.keys(customThemes) as ThemeName[]).filter(
  name => !hiddenThemes.includes(name),
);
